config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'authentication/sessions',
    registrations: 'authentication/registrations'
  }

  namespace :leader do
    root 'home#index'
  end

  root 'leader/home#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization
  include Pagy::Backend

  rescue_from Pundit::NotAuthorizedError, with: :not_authorized

  def self.only_turbo_stream_for(*actions)
    raise ArgumentError, 'force_turbo_stream_for arguments must have least one item' if actions.blank?

    before_action :ensure_turbo_frame_request, only: actions
  end

  def send_flash_message(message:, success: true, now: false)
    type = success ? :notice : :alert
    (now ? flash.now : flash)[type] = message
  end

  private

  def not_authorized
    redirect_to root_path, alert: 'You are not authorized to perform this action.'
  end

  def ensure_turbo_frame_request
    head :bad_request unless turbo_frame_request?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application/_aside.slim
aside.navbar.navbar-vertical.navbar-expand-lg.navbar-dark
  .container-fluid
    button.navbar-toggler data-bs-target='#navbar-menu' data-bs-toggle='collapse' type='button'
      span.navbar-toggler-icon
    h1.navbar-brand.navbar-brand-autodark
      / = link_to leader_root_path
      /   = image_pack_tag 'logo-light.svg', alt: 'Tabler', class: 'navbar-brand-image'
    .navbar-nav.flex-row.d-lg-none
    #navbar-menu.collapse.navbar-collapse
      ul.navbar-nav.pt-lg-3
        li.nav-item class=active_link_class(['leader/home#index'])
          = link_to leader_root_path, class: 'nav-link'
            span.nav-link-icon.d-md-none.d-lg-inline-block.material-icons.material-icons-outlined dashboard
            span.nav-link-title
              | Dashboard

        li.nav-item[class="#{active_link_class(['manager/contacts#index'])}"]
          = link_to "#", class: 'nav-link'
            span.nav-link-icon.d-md-none.d-lg-inline-block.material-icons.material-icons-outlined phone_in_talk
            span.nav-link-title
              | Contacts

        li.nav-item class=active_link_class(['manager/person/developer#index'])
          = link_to '#', class: 'nav-link'
            span.nav-link-icon.d-md-none.d-lg-inline-block.material-icons.material-icons-outlined sailing
            span.nav-link-title
              | Developers

        li.nav-item.nav-item-title
          | Blogs

        li.nav-item class=active_link_class(['manager/post_categories'])
          = link_to '#', class: 'nav-link'
            span.nav-link-icon.d-md-none.d-lg-inline-block.material-icons.material-icons-outlined category
            span.nav-link-title
              | Categories

        li.nav-item class=active_link_class(['manager/posts'])
          = link_to '#', class: 'nav-link'
            span.nav-link-icon.d-md-none.d-lg-inline-block.material-icons.material-icons-outlined web_stories
            span.nav-link-title
              | Posts

        li.nav-item.nav-item-title
          | Settings

        li.nav-item class=active_link_class(['manager/frameworks'])
          = link_to '#', class: 'nav-link'
            span.nav-link-icon.d-md-none.d-lg-inline-block.material-icons.material-icons-outlined shield_moon
            span.nav-link-title
              | Frameworks

        li.nav-item class=active_link_class(['manager/programming_languages'])
          = link_to '#', class: 'nav-link'
            span.nav-link-icon.d-md-none.d-lg-inline-block.material-icons.material-icons-outlined local_fire_department
            span.nav-link-title
              | Languages

        li.nav-item class=active_link_class(['manager/universities#index'])
          = link_to '#', class: 'nav-link'
            span.nav-link-icon.d-md-none.d-lg-inline-block.material-icons.material-icons-outlined school
            span.nav-link-title
              | Universities

        li.nav-item class=active_link_class(['manager/skills'])
          = link_to '#', class: 'nav-link'
            span.nav-link-icon.d-md-none.d-lg-inline-block.material-icons.material-icons-outlined color_lens
            span.nav-link-title
              | Skills

app/views/layouts/application/_header.slim
header.navbar.navbar-expand-md.navbar-light.d-none.d-lg-flex.d-print-none
  .container-xl
    .navbar-nav.flex-row.order-md-last
      .d-none.d-md-flex
        a.nav-link.px-0.hide-theme-dark[href="?theme=dark" data-bs-toggle="tooltip" data-bs-placement="bottom"]
          svg.icon[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"]
            path[stroke="none" d="M0 0h24v24H0z" fill="none"]
            path[d="M12 3c.132 0 .263 0 .393 0a7.5 7.5 0 0 0 7.92 12.446a9 9 0 1 1 -8.313 -12.454z"]
        a.nav-link.px-0.hide-theme-light[href="?theme=light" data-bs-toggle="tooltip" data-bs-placement="bottom"]
          svg.icon[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"]
            path[stroke="none" d="M0 0h24v24H0z" fill="none"]
            circle[cx="12" cy="12" r="4"]
            path[d="M3 12h1m8 -9v1m8 8h1m-9 8v1m-6.4 -15.4l.7 .7m12.1 -.7l-.7 .7m0 11.4l.7 .7m-12.1 -.7l-.7 .7"]
        .nav-item.dropdown.d-none.d-md-flex.me-3
          a.nav-link.px-0[href="#" data-bs-toggle="dropdown" tabindex="-1" aria-label="Show notifications"]
            svg.icon[xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewbox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"]
              path[stroke="none" d="M0 0h24v24H0z" fill="none"]
              path[d="M10 5a2 2 0 0 1 4 0a7 7 0 0 1 4 6v3a4 4 0 0 0 2 3h-16a4 4 0 0 0 2 -3v-3a7 7 0 0 1 4 -6"]
              path[d="M9 17v1a3 3 0 0 0 6 0v-1"]
            span.badge.bg-red
          .dropdown-menu.dropdown-menu-arrow.dropdown-menu-end.dropdown-menu-card
            .card
              .card-header
                h3.card-title
                  | Last updates
              .list-group.list-group-flush.list-group-hoverable
                .list-group-item
                  .row.align-items-center
                    .col-auto
                      span.status-dot.status-dot-animated.bg-red.d-block
                    .col.text-truncate
                      a.text-body.d-block[href="#"]
                        | Todo
                      .d-block.text-muted.text-truncate.mt-n1
                        | Make more fucking awesome features!
      .nav-item.dropdown
        a.nav-link.d-flex.lh-1.text-reset.p-0 aria-label=("Open user menu") data-bs-toggle="dropdown" href="#"
          span.avatar.avatar-sm
            | B
          .d-none.d-xl-block.ps-2
            div
              = current_user&.email
            .mt-1.small.text-muted
              | Admin
        .dropdown-menu.dropdown-menu-end.dropdown-menu-arrow
          = link_to 'Profile Settings', edit_user_registration_path, class: 'dropdown-item'
          .dropdown-divider
          = link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete }, class: 'dropdown-item'
    .collapse.navbar-collapse
      .input-icon
          input.form-control placeholder="Search…" type="text"
          span.input-icon-addon
            svg.icon fill="none" height="24" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox=("0 0 24 24") width="24" xmlns="http://www.w3.org/2000/svg"
              path d=("M0 0h24v24H0z") fill="none" stroke="none"
              circle cx="10" cy="10" r="7"
              line x1="21" x2="15" y1="21" y2="15"